---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mautrix-bridge-base
  labels:
    app.kubernetes.io/name: mautrix-facebook
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mautrix-facebook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mautrix-facebook
    spec:
      serviceAccountName: mautrix-facebook-bridge
      containers:
        - name: mautrix-bridge
          image: "dock.mau.dev/mautrix/facebook:v0.5.1"
          command:
            - python3
            - -m
            - mautrix_facebook
            - -c
            - /data/config.yaml
      volumes:
        - name: config
          configMap:
            name: mautrix-facebook-bridge
        - name: secret
          secret:
            secretName: mautrix-facebook-bridge
        - name: data
          emptyDir: {}

