---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mautrix-bridge-base
  labels:
    app.kubernetes.io/name: mautrix-whatsapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mautrix-whatsapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mautrix-whatsapp
    spec:
      serviceAccountName: mautrix-whatsapp-bridge
      containers:
        - name: mautrix-bridge
          image: "dock.mau.dev/mautrix/whatsapp:v0.2.4"
          command:
          - /usr/bin/mautrix-whatsapp
          - "-n"
          - "-c"
          - "/data/config.yaml"
      volumes:
        - name: config
          configMap:
            name: mautrix-whatsapp-bridge
        - name: secret
          secret:
            secretName: mautrix-whatsapp-bridge
        - name: data
          emptyDir: {}

