---
apiVersion: v1
kind: Service
metadata:
  name: mautrix-whatsapp-bridge
  labels:
    app.kubernetes.io/name: mautrix-whatsapp
    app.kubernetes.io/instance: matrix-whatsapp
spec:
  type: ClusterIP
  ports:
    - port: 29318
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mautrix-whatsapp
    app.kubernetes.io/instance: matrix-whatsapp
