---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mautrix-bridge-base
spec:
  replicas: 1
  strategy:
    rollingUpdates: null
    type: Recreate
  template:
    spec:
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      initContainers:
        - name: init
          image: "linuxserver/yq"
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args:
            - "-c"
            - |-
              set -ex
              yq -s '.[0] * .[1]' /config/config.yaml /secret/config.yaml > /data/config.yaml
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /config
            - name: secret
              mountPath: /secret
      containers:
        - name: mautrix-bridge
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 29318
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_matrix/mau/live
              port: http
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_matrix/mau/live
              port: http
            failureThreshold: 5
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /_matrix/mau/live
              port: http
            initialDelaySeconds: 5
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
