---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mautrix-bridge-base
  labels:
    app.kubernetes.io/name: mautrix-telegram
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mautrix-telegram
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mautrix-telegram
    spec:
      serviceAccountName: mautrix-telegram-bridge
      containers:
        - name: mautrix-bridge
          image: "dock.mau.dev/mautrix/telegram:v0.15.1"
          command:
            - python3
            - -m
            - mautrix_telegram
            - -c
            - /data/config.yaml
      volumes:
        - name: config
          configMap:
            name: mautrix-telegram-bridge
        - name: secret
          secret:
            secretName: mautrix-telegram-bridge
        - name: data
          emptyDir: {}

